sudo: false
language: node_js
node_js:
  - 16.3
cache: npm
branches:
  only:
    - source
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public

